### ISSUE TITLE
Cross-lingual experiments

### ISSUE THREAD

**Issue by iezhanqingran** [sciforce/phones-las#15]
Hi,

I am doing some ASR experiments using AFs and I found your work, which is fantastic work.

And I noticed that you mentioned this framework can extend to cross-lingual ASR, Did you already have some papers?

Meanwhile, I am trying to replicate your work, hope it goes well

Thanks in advance

**Comment by akademi4eg** [comment]
Hi @iezhanqingran 

We tried multilingual training and now are conducting cross-lingual experiments. We haven't published yet, but have plans to do so next year (maybe for Interspeech 2020).

Let me know if you have any issues with training.
Also note that current master branch have some updates and improvements relatively to what we had in the paper. As far as I remember, `v1.0` tag corresponds to what we had at paper time.

**Comment by iezhanqingran** [comment]
Thanks! I'll try v1.0.

**Comment by iezhanqingran** [comment]
Hi, for the espeak-ng package, it looks like it requires root when "make install"
But for me I have no root privileges. Do you have ideas how to solve it ?
Thanks.

**Comment by akademi4eg** [comment]
If you don't have access to `sudo` or other way to escalate user privileges, than you should install in a folder where you have access. For example, to your home directory. To do so, during configure phase you need to change prefix:
`./configure --prefix=/home/iezhanqingran/apps`

This way after building espeak-ng, `make install` would install to `/home/iezhanqingran/apps` directory.

After successful installation you'll also need to add `/home/iezhanqingran/apps/bin` to your PATH variable.

So, full example (assuming your home directory):
```
./configure --prefix $HOME/apps
make
make install
export PATH="$PATH:$HOME/apps"
espeak-ng -f some_text_file.txt --ipa
```

**Comment by iezhanqingran** [comment]
Thank you for your prompt reply!  
Now it works for me and I'll try to train the model

**Comment by iezhanqingran** [comment]
Hi,
I want to train a model to predict the articulatory features and I follow the recipe and prepared the file like this:
database/timit/timit/train/dr1/fcjf0/sa1.wav,en,sil sh ih hh eh sil jh ih sil d ah sil k s uw n sil g r ih s ih w aa sh sil w aa dx er aa l y ih er sil.

When I run preprocess_all.py, 
python3 preprocess_all.py --input_file data/train_tmp_2.csv  --output_file data/train                                                                                                               --targets binary_features 
I run the following command and I got the error: Failed to convert text to IPA

and I changed targets: binary_feature to words it goes well. Because what I want to do is to detect
the aritculatory features as your paper, Should I set the targets to binary_features and how to solve this error?

**Comment by akademi4eg** [comment]
`--binary_features` option is necessary for training with plain articulatory features targets. We didn't find it to give any benefits against training with articulatory features as proxy to phones.

So for TIMIT you should run `preprocess_all.py` with words targets. Training data would have only phones labels, and articulatory features would be extracted at training phase using mapping from `misc` folder.

For proper training you would need to pass `--binf_map`, `--binary_outputs` and possibly `--output_ipa` parameters.

On current master branch train call would look similar to this:
`python3 ./train.py --train timit/e_step.tfrecord --valid timit/test.tfrecord --vocab timit/vocab.txt --norm timit/norm.dmp --model_dir timit/model --encoder_units 256 --encoder_layers 3 --decoder_units 256 --decoder_layers 1 --attention_type luong --num_channels 42  --batch_size 32 --learning_rate 1e-3 --eval_secs 300 --use_pyramidal --num_epochs 150 --binary_outputs --output_ipa --binf_projection --binf_map misc/binf_map_arpabet_extended.csv  --ctc_weight 0 --l2_reg_scale 1e-5 --add_noise 0 --dropout 0.4 --sampling_probability 0.2 --reset`

On `v1.0` tag you might need to drop `--binf_projection` parameter as it wasn't introduced yet.

**Comment by iezhanqingran** [comment]
Thanks! I'll try it.

**Comment by iezhanqingran** [comment]
Hi, I run the code using the follwing parameters:
 `python3 /idiap/temp/qzhan/phone-las-tmp/preprocess_all.py --input_file data/timit_tmp/train.csv    --output_file data/timit_tmp/train.tfrecord      --targets words`

`python3 -u  train.py --train data/timit_tmp/train.tfrecord --valid data/timit_tmp/train.tfrecord --vocab misc/vocab.txt  --model_dir timit/model --encoder_units 256 --encoder_layers 3 --decoder_units 256 --decoder_layers 1 --attention_type luong --num_channels 42 --batch_size 32 --learning_rate 1e-3 --eval_secs 300 --use_pyramidal --num_epochs 150 --binary_outputs --output_ipa --binf_map misc/binf_map_arpabet.csv --l2_reg_scale 1e-5 --add_noise 0 --dropout 0.4 --sampling_probability 0.2 --reset`
And I got the following errors:
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_evaluation_master': '', '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_log_step_count_steps': 100, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f161598b908>, '_save_checkpoints_steps': None, '_task_id': 0, '_model_dir': 'timit/model', '_keep_checkpoint_max': 5, '_device_fn': None, '_master': '', '_service': None, '_num_worker_replicas': 1, '_task_type': 'worker', '_save_summary_steps': 100, '_num_ps_replicas': 0, '_train_distribute': None, '_experimental_distribute': None, '_protocol': None, '_tf_random_seed': None, '_keep_checkpoint_every_n_hours': 10000, '_global_id_in_cluster': 0, '_eval_distribute': None}
INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Building listener
INFO:tensorflow:Building speller
INFO:tensorflow:Trainable parameters: 6417424
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2020-01-20 17:49:08.486778: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Restoring parameters from timit/model/model.ckpt-0
Traceback (most recent call last):
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1296,1024] rhs shape= [1322,1024]
	 [[{{node save/Assign_41}} = Assign[T=DT_FLOAT, _class=["loc:@speller/decoder/attention_wrapper/multi_rnn_cell/cell_0/lstm_cell/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](speller/decoder/attention_wrapper/multi_rnn_cell/cell_0/lstm_cell/kernel/Adam, save/RestoreV2:41)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1546, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1296,1024] rhs shape= [1322,1024]
	 [[node save/Assign_41 (defined at train.py:159)  = Assign[T=DT_FLOAT, _class=["loc:@speller/decoder/attention_wrapper/multi_rnn_cell/cell_0/lstm_cell/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](speller/decoder/attention_wrapper/multi_rnn_cell/cell_0/lstm_cell/kernel/Adam, save/RestoreV2:41)]]

Caused by op 'save/Assign_41', defined at:
  File "train.py", line 170, in <module>
    main(args)
  File "train.py", line 159, in main
    tf.estimator.train_and_evaluate(model, train_spec, eval_spec)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1468, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 504, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 921, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 643, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1107, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1112, in _create_session
    return self._sess_creator.create_session()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 800, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 557, in create_session
    self._scaffold.finalize()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 215, in finalize
    self._saver.build()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 789, in _build_internal
    restore_sequentially, reshape)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 459, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 428, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 119, in restore
    self.op.get_shape().is_fully_defined())
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1296,1024] rhs shape= [1322,1024]
	 [[node save/Assign_41 (defined at train.py:159)  = Assign[T=DT_FLOAT, _class=["loc:@speller/decoder/attention_wrapper/multi_rnn_cell/cell_0/lstm_cell/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](speller/decoder/attention_wrapper/multi_rnn_cell/cell_0/lstm_cell/kernel/Adam, save/RestoreV2:41)]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 170, in <module>
    main(args)
  File "train.py", line 159, in main
    tf.estimator.train_and_evaluate(model, train_spec, eval_spec)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1468, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 504, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 921, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 643, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1107, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1112, in _create_session
    return self._sess_creator.create_session()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 800, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 566, in create_session
    init_fn=self._scaffold.init_fn)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 288, in prepare_session
    config=config)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 218, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1582, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1296,1024] rhs shape= [1322,1024]
	 [[node save/Assign_41 (defined at train.py:159)  = Assign[T=DT_FLOAT, _class=["loc:@speller/decoder/attention_wrapper/multi_rnn_cell/cell_0/lstm_cell/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](speller/decoder/attention_wrapper/multi_rnn_cell/cell_0/lstm_cell/kernel/Adam, save/RestoreV2:41)]]

Caused by op 'save/Assign_41', defined at:
  File "train.py", line 170, in <module>
    main(args)
  File "train.py", line 159, in main
    tf.estimator.train_and_evaluate(model, train_spec, eval_spec)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1468, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 504, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 921, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 643, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1107, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1112, in _create_session
    return self._sess_creator.create_session()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 800, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 557, in create_session
    self._scaffold.finalize()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 215, in finalize
    self._saver.build()
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 789, in _build_internal
    restore_sequentially, reshape)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 459, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 428, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 119, in restore
    self.op.get_shape().is_fully_defined())
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/idiap/home/qzhan/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs **shape= [1296,1024] rhs shape= [1322,1024]**
	 [[node save/Assign_41 (defined at train.py:159)  = Assign[T=DT_FLOAT, _class=["loc:@speller/decoder/attention_wrapper/multi_rnn_cell/cell_0/lstm_cell/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](speller/decoder/attention_wrapper/multi_rnn_cell/cell_0/lstm_cell/kernel/Adam, save/RestoreV2:41)]]

Can you please check it and give some suggestions?

**Comment by akademi4eg** [comment]
Hi @iezhanqingran 
Sorry for a long delay.
I think you need to remove contents of `timit/model` directory as there is a conflict during save operation (**save/Assign_41**).

A few other notes:
1. I'd recommend using `--norm` and `--deltas` parameters for `preprocess_all` to get better results. `--norm` should also be passed to `train.py` then.
2. Without deltas you'd have to set `--num_channels` to 13 instead of 42 (42 is a value for mfcc with deltas and energy: (13 + 1) * 3).
3. On current `master` after running preprocess_all as in your message, train works for me if I add `--binf_projection` parameter.

**Comment by akademi4eg** [comment]
Closing due to inactivity. Feel free to reopen if you have any further issues.
